TOOL_VERSION = "0.8.0"
TOOL_NAME = "jocasta"

ARCHIVE_FILE_SUFFIX = "_archives"
ARCHIVE_FILE_TYPE_SUFFIXES = ["lua", "json"]
META_FILE_NAME = "meta.yaml"
META_FILE_NAME_JSON = "meta.json"
ENTRY_FILE_NAME = "entry.md"

TRUNCATION_SEQUENCE = "..."
PROGRESS_BAR_CHARACTER = "#"
HELP_TEXT_VALUE_DELIMITER = "/"
