name: archive-process

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install toml==0.10.2
      - run: pip install mdformat-gfm==0.3.6
      - run: python jocasta.py -vvv --format
      - run: python jocasta.py -vvv --generate-meta
      - run: python jocasta.py --check