name: archive-process

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install toml
      - run: pip install mdformat-gfm
      - run: python jocasta.py --format
      - run: python jocasta.py --generate-meta
      - run: python jocasta.py --check